#!/bin/bash
DATE=`date +%Y-%m-%d`
cd /tmp/
rm -rf dump
mongodump --db voteview -c voteview_rollcalls
mongodump --db voteview -c voteview_members
mongodump --db voteview -c voteview_parties
zip $DATE-voteview.zip dump/voteview/*
# rm -rf dump
mv $DATE-voteview.zip /var/www/voteview/static/db/
cd /var/www/voteview/static/db/
ls -tp | grep -v '/$' | tail -n +10 | xargs -I {} rm -- {}
unlink current.zip
ln -s $DATE-voteview.zip current.zip
